2023-06-16 00:11:41,234 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 51, in distribution
    print("parser: ", app.config["PRETRAIN_MODEL_CHECKPOINT"])
AttributeError: module 'flask.app' has no attribute 'config'
2023-06-16 00:16:33,173 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 50, in distribution
    print("===========: ", current_app.config.to_dict())
AttributeError: 'Config' object has no attribute 'to_dict'
2023-06-16 00:19:20,980 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 52, in distribution
    print("===========: ", config_dict.SAMPLE_DB_PASSWORD)
AttributeError: 'dict' object has no attribute 'SAMPLE_DB_PASSWORD'
2023-06-16 00:19:42,288 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 53, in distribution
    print("===========: ", json.loads(config_dict).SAMPLE_DB_PASSWORD)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
2023-06-16 00:19:59,097 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 53, in distribution
    print("===========: ", json.dumps(config_dict).SAMPLE_DB_PASSWORD)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type timedelta is not JSON serializable
2023-06-16 00:23:23,989 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 51, in distribution
    config_dict[key] = current_app.config[key]
TypeError: 'object' object does not support item assignment
2023-06-16 13:57:05,952 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 56, in distribution
    tbls = table_statistics(args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 336, in table_statistics
    conn = psycopg2.connect(**source_db_credentials)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "166.111.121.55" and accepting
	TCP/IP connections on port 54322?

2023-06-16 13:59:41,750 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 56, in distribution
    tbls = table_statistics(args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 355, in table_statistics
    cursor.execute(f"""
psycopg2.InterfaceError: cursor already closed
2023-06-16 14:03:05,153 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 56, in distribution
    tbls = table_statistics(args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 367, in table_statistics
    cursor.execute(f"""
psycopg2.InterfaceError: cursor already closed
2023-06-16 14:16:22,824 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 56, in distribution
    tbls = table_statistics(args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 368, in table_statistics
    cursor.execute(f"""
psycopg2.InterfaceError: cursor already closed
2023-06-16 14:16:49,948 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 56, in distribution
    tbls = table_statistics(args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 349, in table_statistics
    conn = psycopg2.connect(**source_db_credentials)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 121, in connect
    dsn = _ext.make_dsn(dsn, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/psycopg2/extensions.py", line 167, in make_dsn
    parse_dsn(dsn)
psycopg2.ProgrammingError: invalid dsn: invalid connection option "timeout"

2023-06-16 14:19:14,205 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 56, in distribution
    tbls = table_statistics(args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 349, in table_statistics
    conn = psycopg2.connect(**source_db_credentials)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 121, in connect
    dsn = _ext.make_dsn(dsn, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/psycopg2/extensions.py", line 167, in make_dsn
    parse_dsn(dsn)
psycopg2.ProgrammingError: invalid dsn: invalid connection option "statement_timeout"

2023-06-16 14:19:52,675 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 56, in distribution
    tbls = table_statistics(args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 369, in table_statistics
    cursor.execute(f"""
psycopg2.InterfaceError: cursor already closed
2023-06-16 14:32:40,428 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 60, in distribution
    graph = Column2Graph(args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/partition_selection/selection_model.py", line 24, in __init__
    self.schema = database.table_col(self.args.schema_name)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 20, in table_col
    with open(file_name, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/tpch_demo/schema.sql'
2023-06-16 14:34:56,968 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 60, in distribution
    graph = Column2Graph(args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/partition_selection/selection_model.py", line 24, in __init__
    self.schema = database.table_col(self.args.schema_name)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 26, in table_col
    with open(file_name, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/tpch_demo/schema.sql'
2023-06-16 16:42:20,147 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 56, in distribution
    tbls = table_statistics(args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 355, in table_statistics
    conn = psycopg2.connect(**source_db_credentials)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "gpadmin"

2023-06-16 16:43:20,740 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 57, in distribution
    tbls = table_statistics(args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 355, in table_statistics
    conn = psycopg2.connect(**source_db_credentials)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "gpadmin"

2023-06-16 16:49:54,602 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 57, in distribution
    tbls = table_statistics(args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 355, in table_statistics
    conn = psycopg2.connect(**source_db_credentials)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "gpadmin"

2023-06-16 16:50:22,448 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 57, in distribution
    tbls = table_statistics(args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 355, in table_statistics
    conn = psycopg2.connect(**source_db_credentials)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "gpadmin"

2023-06-16 16:51:11,660 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 57, in distribution
    tbls = table_statistics(args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 355, in table_statistics
    conn = psycopg2.connect(**source_db_credentials)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "gpadmin"

2023-06-16 16:55:47,512 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 62, in distribution
    tbls = table_statistics(args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 355, in table_statistics
    conn = psycopg2.connect(**source_db_credentials)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "gpadmin"

2023-06-16 17:02:53,914 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 61, in distribution
    tbls = table_statistics(args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 355, in table_statistics
    conn = psycopg2.connect(**source_db_credentials)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "gpadmin"

2023-06-16 17:18:28,258 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 65, in distribution
    graph = Column2Graph(args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/partition_selection/selection_model.py", line 24, in __init__
    self.schema = database.table_col(self.args.schema_path)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 26, in table_col
    with open(parent_path+file_name, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/datasets/tpch_demo/schema.sql'
2023-06-16 17:19:36,715 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 35, in wrapper
    return jsonify(rv)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 297, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/core.py", line 30, in default
    return super(JSONEncoder, self).default(o)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tensor is not JSON serializable
2023-06-16 17:21:42,698 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 35, in wrapper
    return jsonify(rv)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 297, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/core.py", line 30, in default
    return super(JSONEncoder, self).default(o)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tensor is not JSON serializable
2023-06-16 17:22:32,100 [app_factory] [ERROR] :40: Exception on /partition/recommend [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 20, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 103, in recommend
    partition_keys = test_partition_key_selection()
TypeError: test_partition_key_selection() missing 1 required positional argument: 'args'
2023-06-16 17:55:11,849 [app_factory] [ERROR] :40: Exception on /partition/preview [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 21, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 161, in preview
    database.alter_partition_keys(args, partition_keys)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 470, in alter_partition_keys
    query = "ALTER TABLE {} SET DISTRIBUTED BY ({})".format(table_name, args.partition_keys[table_name])
AttributeError: 'PartitionConfig' object has no attribute 'partition_keys'
2023-06-16 17:57:09,970 [app_factory] [ERROR] :40: Exception on /partition/preview [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 21, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 157, in preview
    database.alter_partition_keys(args, partition_keys)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 471, in alter_partition_keys
    cursor.execute(query)
psycopg2.errors.SyntaxError: syntax error at or near "["
LINE 1: ALTER TABLE lineitem SET DISTRIBUTED BY (['l_quantity', 'l_s...
                                                 ^

2023-06-16 17:58:48,703 [app_factory] [ERROR] :40: Exception on /partition/preview [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 21, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 157, in preview
    database.alter_partition_keys(args, partition_keys)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 471, in alter_partition_keys
    cursor.execute(query)
psycopg2.errors.SyntaxError: syntax error at or near "["
LINE 1: ALTER TABLE lineitem SET DISTRIBUTED BY (['l_orderkey', 'l_q...
                                                 ^

2023-06-16 18:00:08,784 [app_factory] [ERROR] :40: Exception on /partition/preview [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 36, in wrapper
    return jsonify(rv)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 297, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/core.py", line 30, in default
    return super(JSONEncoder, self).default(o)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SampleGraph is not JSON serializable
2023-06-16 21:45:22,904 [app_factory] [ERROR] :40: Exception on /partition/preview [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 36, in wrapper
    return jsonify(rv)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 297, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/core.py", line 30, in default
    return super(JSONEncoder, self).default(o)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tensor is not JSON serializable
2023-06-16 21:54:23,724 [app_factory] [ERROR] :40: Exception on /partition/preview [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 36, in wrapper
    return jsonify(rv)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 297, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/core.py", line 30, in default
    return super(JSONEncoder, self).default(o)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tensor is not JSON serializable
2023-06-16 21:54:41,420 [app_factory] [ERROR] :40: Exception on /partition/preview [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 36, in wrapper
    return jsonify(rv)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 297, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/core.py", line 30, in default
    return super(JSONEncoder, self).default(o)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tensor is not JSON serializable
2023-06-16 21:56:22,992 [app_factory] [ERROR] :40: Exception on /partition/preview [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 36, in wrapper
    return jsonify(rv)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 297, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/core.py", line 30, in default
    return super(JSONEncoder, self).default(o)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tensor is not JSON serializable
2023-06-16 21:56:47,693 [app_factory] [ERROR] :40: Exception on /partition/preview [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 36, in wrapper
    return jsonify(rv)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 297, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/core.py", line 30, in default
    return super(JSONEncoder, self).default(o)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tensor is not JSON serializable
2023-06-18 21:55:59,443 [app_factory] [ERROR] :40: Exception on /partition/dataset [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 21, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 28, in dataset
    datasets = get_dataset_names()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 84, in get_dataset_names
    for dir_name in os.listdir(dataset_path):
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/datasets'
2023-06-18 21:59:42,733 [app_factory] [ERROR] :40: Exception on /partition/dataset [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 21, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 28, in dataset
    datasets = get_dataset_names()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 83, in get_dataset_names
    for dir_name in os.listdir(dataset_path):
FileNotFoundError: [Errno 2] No such file or directory: '/datasets'
2023-06-18 22:01:58,611 [app_factory] [ERROR] :40: Exception on /partition/dataset [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 21, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 28, in dataset
    datasets = get_dataset_names()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 84, in get_dataset_names
    for dir_name in os.listdir(dataset_path):
FileNotFoundError: [Errno 2] No such file or directory: '/datasets'
2023-06-18 22:35:15,205 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 21, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 59, in distribution
    tbls = table_statistics(args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/services/partition/database/database.py", line 348, in table_statistics
    conn = psycopg2.connect(**source_db_credentials)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "166.111.121.55" and accepting
	TCP/IP connections on port 54322?

2023-06-19 18:26:01,953 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 37, in wrapper
    return jsonify(rv)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 297, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected
2023-06-19 18:26:47,997 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 37, in wrapper
    return jsonify(rv)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 297, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Circular reference detected
2023-06-19 18:29:33,168 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 37, in wrapper
    return jsonify(rv)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 297, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/core.py", line 30, in default
    return super(JSONEncoder, self).default(o)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type dict_values is not JSON serializable
2023-06-19 18:39:34,854 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 22, in wrapper
    rv = f(*args, **kwargs)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/partition.py", line 88, in distribution
    edge_json[key]['line']['width'] = min(max(edge_json[key]['value'], 1), 20),
KeyError: 'line'
2023-06-19 18:41:49,084 [app_factory] [ERROR] :40: Exception on /partition/distribution [POST]
Traceback (most recent call last):
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/util.py", line 37, in wrapper
    return jsonify(rv)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 297, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 131, in dumps
    return _json.dumps(obj, **kwargs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/api/utils/core.py", line 30, in default
    return super(JSONEncoder, self).default(o)
  File "/Volumes/NBDATA/JobProjects/Tsinghua/DatabasePartitionDemo/demo_database_partition/venv/lib/python3.9/site-packages/flask/json/__init__.py", line 50, in default
    return super().default(o)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
